[package]
name = "osekkai-chan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = { optional = true, version = "=0.15.7" }
futures = "=0.3.29"
tokio = { version = "=1.35.0", features = ["full"] }
tracing = "=0.1.40"
twilight-cache-inmemory = "=0.15.4"
twilight-gateway = "=0.15.4"
twilight-http = "=0.15.4"
twilight-mention = "=0.15.3"
twilight-model = "=0.15.4"
twilight-standby = "=0.15.4"
twilight-util = { version = "=0.15.4", features = ["builder"] }

[[bin]]
name = "osekkai-chan"
path = "main.rs"

[features]
default = ["dotenv"]
dotenv = ["dep:dotenvy"]
