name: build
on:
  push:
    branches: [main]
    tags: [v*.*.*]
  pull_request:
  workflow_call:
    inputs:
      tag-name:
        required: true
        type: string
    outputs:
      image_tags:
        value: ${{ jobs.image.outputs.image_tags }}
      image_url:
        value: https://ghcr.io/${{ github.repository }}

env:
  # const
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  # env
  RUSTFLAGS: "-Dwarnings"

jobs:
  env:
    if: ${{ !( github.workflow == 'build' && startsWith(github.event.head_commit.message, 'release:') && github.event.head_commit.author.name == 'mazi-release[bot]' ) }}
    runs-on: ubuntu-latest
    outputs:
      BINARY_NAME: ${{ steps.meta.outputs.BINARY_NAME }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - id: meta
        run: |
          echo "BINARY_NAME=$(cargo metadata --offline --no-deps --format-version=1 | jq -r '.packages[].targets[] | select(.kind | map(. == "bin") | any ) | .name')" >> $GITHUB_OUTPUT

  build:
    needs: [env]
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        profile: ${{ github.ref_name == github.event.repository.default_branch && fromJson('["dev", "release"]') || fromJson('["dev"]') }}
        platform:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            command: cross
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
            command: cross
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            command: cargo
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            command: cargo
          - target: aarch64-apple-darwin
            os: macos-latest
            command: cargo
          - target: x86_64-apple-darwin
            os: macos-latest
            command: cargo
    runs-on: ${{ matrix.platform.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
    defaults:
      run:
        shell: bash -xe {0}
    steps:
      - name: Install musl tools
        if: matrix.platform.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt-get install -y musl-tools --no-install-recommends
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
      - uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
        with:
          key: ${{ matrix.profile }}-${{ matrix.platform.target }}
      - name: Install cross
        if: ${{ matrix.platform.command == 'cross' }}
        uses: taiki-e/install-action@4fd6bded9bf87df7896958594ca6d67b38b5350e # v2.56.15
        with:
          tool: cross
      - run: mkdir dist
      - run: ${{ matrix.platform.command }} rustc --locked ${{ matrix.profile == 'release' && '--release' || '' }} --no-default-features --target=${{ matrix.platform.target }} -- --emit=link=dist/${{ needs.env.outputs.BINARY_NAME }}
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ matrix.profile }}-${{ matrix.platform.target }}
          path: |
            dist/${{ needs.env.outputs.BINARY_NAME }}
            dist/${{ needs.env.outputs.BINARY_NAME }}.exe
      - name: Upload to release
        if: ${{ inputs.tag-name && matrix.profile == 'release' }}
        working-directory: dist/
        run: |
          if [ -e ${{ needs.env.outputs.BINARY_NAME }}.exe ]; then
            filename="${{ needs.env.outputs.BINARY_NAME }}-${{ inputs.tag-name }}-${{ matrix.platform.target }}.exe"
            mv ${{ needs.env.outputs.BINARY_NAME }}.exe "$filename"
            gh release upload ${{ inputs.tag-name }} "$filename"#${{ matrix.platform.target }} --clobber
          else
            filename="${{ needs.env.outputs.BINARY_NAME }}-${{ inputs.tag-name }}-${{ matrix.platform.target }}"
            mv ${{ needs.env.outputs.BINARY_NAME }} "$filename"
            gh release upload ${{ inputs.tag-name }} "$filename"#${{ matrix.platform.target }} --clobber
          fi
  image:
    needs: [env, build]
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      packages: write
    runs-on: "ubuntu-latest"
    outputs:
      image_tags: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: artifact
          pattern: release-*-unknown-linux-musl

      - name: Log in to the Container registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ inputs.tag-name }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.tag-name }}
            type=semver,pattern={{major}},value=${{ inputs.tag-name }},enable=${{ !(startsWith(github.ref, 'refs/tags/v0.') || startsWith(inputs.tag-name, 'v0.')) }}
            type=edge
            type=ref,event=branch

      - name: Build Images
        run: |
          build() {
            newcontainer=$(buildah from --platform="$1" scratch)
            buildah copy --chmod=0755 $newcontainer ./artifact/release-"$2"/${{ needs.env.outputs.BINARY_NAME }} /${{ needs.env.outputs.BINARY_NAME }}
            buildah config --entrypoint='["./${{ needs.env.outputs.BINARY_NAME }}"]' $newcontainer

            buildah config --author="Mogyuchi" $(awk '{print "--label=" $0}' <<< "${{ steps.meta.outputs.labels }}") $newcontainer
            buildah inspect $newcontainer

            buildah commit --manifest=localhost/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }} $newcontainer
            buildah rm $newcontainer
          }
          build linux/amd64 x86_64-unknown-linux-musl
          build linux/arm64 aarch64-unknown-linux-musl

      - id: push
        name: Push To GHCR
        run: |
          buildah manifest inspect localhost/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
          tac <<< '${{ steps.meta.outputs.tags }}' | parallel --halt=now,fail=1 --jobs=1 'buildah manifest push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} --all --digestfile="$RUNNER_TEMP/image-digest" localhost/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }} docker://{} && printf "\`\`\`\n%s@$(cat "$RUNNER_TEMP/image-digest")\n\`\`\`\n" {} >> "$GITHUB_STEP_SUMMARY"'
